### ISSUE TITLE
Computing probability of an external sample

### ISSUE THREAD

**Issue by Ghadjeres** [CW-Huang/NAF#1]
Hi,
Thanks a lot for your awesome work.
Do you plan to implement the methods for computing the logprob of any data point for IAF_DDSF?
Best

**Comment by CW-Huang** [comment]
Hi Gaetan, unfortunately neither DSF nor DDSF has a closed form inverse function, so it would require some sort of numerical approximation method and is not part of our current plan. It might be possible to consider other choice of transformer (other than DSF family) which has a closed form function. Or if you simply need to do density estimation you can use DSF/DDSF in a MAF-style.

**Comment by Ghadjeres** [comment]
Thanks a lot for your answer. 
Yes you're right, or maybe invertible neural networks could be used to this end, like i-revnet, but for the moment I'll just drop the possibility to draw samples and use MAF.
Congratulations again for this great work.
